type = 'EncoderDecoder'
backbone = dict(
    type='HRNet',
    norm_cfg=dict(type='BN', requires_grad=True),
    norm_eval=False,
    extra=dict(
        stage1=dict(
            num_modules=1,
            num_branches=1,
            block='BOTTLENECK',
            num_blocks=(4,),
            num_channels=(64,)),
        stage2=dict(
            num_modules=1,
            num_branches=2,
            block='BASIC',
            num_blocks=(4, 4),
            num_channels=(18, 36)),
        stage3=dict(
            num_modules=4,
            num_branches=3,
            block='BASIC',
            num_blocks=(4, 4, 4),
            num_channels=(18, 36, 72)),
        stage4=dict(
            num_modules=3,
            num_branches=4,
            block='BASIC',
            num_blocks=(4, 4, 4, 4),
            num_channels=(18, 36, 72, 144))))
decode_head = dict(
    type='FCNHead',
    in_channels=[18, 36, 72, 144],
    in_index=(0, 1, 2, 3),
    channels=sum([18, 36, 72, 144]),
    input_transform='resize_concat',
    kernel_size=1,
    num_convs=1,
    concat_input=False,
    dropout_ratio=-1,
    num_classes=19,
    norm_cfg=dict(type='BN', requires_grad=True),
    align_corners=False, )
