type = 'EncoderDecoder'
backbone = dict(
    type='HRNet',
    norm_cfg=dict(type='BN', requires_grad=True),
    norm_eval=False,
    extra=dict(
        stage1=dict(
            num_modules=1,
            num_branches=1,
            block='BOTTLENECK',
            num_blocks=(4,),
            num_channels=(64,)),
        stage2=dict(
            num_modules=1,
            num_branches=2,
            block='BASIC',
            num_blocks=(4, 4),
            num_channels=(18, 36)),
        stage3=dict(
            num_modules=4,
            num_branches=3,
            block='BASIC',
            num_blocks=(4, 4, 4),
            num_channels=(18, 36, 72)),
        stage4=dict(
            num_modules=3,
            num_branches=4,
            block='BASIC',
            num_blocks=(4, 4, 4, 4),
            num_channels=(18, 36, 72, 144))))
decode_head = dict(
    type='UPerHead',
    in_channels=[48, 96, 192, 384],
    pool_scales=[1, 2, 3, 6],
    in_index= [0, 1, 2, 3],
    dropout_ratio=0.1,
    channels=512,
    align_corners=False,
    norm_cfg=dict(type='BN',
                  requires_grad=True))
