type: 'EncoderDecoder'
backbone:
    type: 'SwinTransformer'
    embed_dim: 128
    depths: [2, 2, 18, 2]
    num_heads: [4, 8, 16, 32]
    in_chans: 1
    window_size: 7
    mlp_ratio: 4.
    qkv_bias: True
    qk_scale:
    drop_rate: 0.
    attn_drop_rate: 0.
    drop_path_rate: 0.3
    ape: False
    patch_norm: True
    out_indices: [0, 1, 2, 3]
    use_checkpoint: True
decode_head:
    type: 'UPerHead'
    in_channels: [128, 256, 512, 1024]
    in_index: [0, 1, 2, 3]
    pool_scales: [1, 2, 3, 6]
    channels: 512
    dropout_ratio: 0.1
    num_classes: 1
    norm_cfg:
        type: 'BN'
        requires_grad: True
    align_corners: False

