_Base_Config: 'configs/_base/network/muti_model/single_model_unet-r50.yaml'
# Model Configuration #########################################################
network:
    name_list: ['ARUNet', 'ARUNet']
    post_process:
        module_path: wss.muti_model_post_process
        name: MultiModelBinarySemanticSegmentationPostProcess
        model_weight_list: [0.5, 0.5]
        mask_threshold: 0.5

