_Base_Config: 'configs/_base/network/muti_model/single_model_hnn-r50.yaml'
# Model Configuration #########################################################
network:
    name: MutiParallelModel
    name_list: ['HNN', 'HNN']
    post_process:
        name: MultiModelBinarySemanticSegmentationPostProcess
        model_weight_list: [0.5, 0.5]
        mask_threshold: 0.5

