_Base_Config: 'configs/_base/runner/dual_consistency/basic_fully_supervised_semantic_segmentation.yaml'
# Running Configuration ######################################################
run:
    loss:
        name: CoSegLoss
        cfg:
            supv_loss: dice_loss
            cons_loss: dice_loss
            cons_delay: -1
            epoch_delay: 500
            model_num: 2
            weight: [1, 0.4]

